### ISSUE TITLE
Tweaks needed in snippet preview and <pre> blocks

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#1]
The blocks contained within `div.snippet_preview` DIVs look like they still need some love. `span.sssh-property` is still black-on-black.

To reproduce, create a code snippet with Python highlighting and dump this code into it:

``` python
>>> import timeit
>>> t1 = timeit.Timer('"{0}/{1}".format(x, y)', 'x = "foo"; y = "bar"')
>>> t2 = timeit.Timer('"/".join((x, y))', 'x = "foo"; y = "bar"')
>>> t1.repeat()
[0.4785940647125244, 0.43045902252197266, 0.4402921199798584]
>>> t2.repeat()
[0.31827497482299805, 0.2677180767059326, 0.2675449848175049]
>>>
```

The "Timer" text will be invisible. This is similar to a fix you recently did for syntax highlighting, just needs to be made here as well.

Also, `pre.special_formatting` (triple-backtick-enclosed blocks of text) displays mentions (`span.mention`) as grey-on-magenta.

Thanks!

**Comment by laCour** [comment]
Thanks!

I'm unable to replicate the second issue you mentioned though. Mentions in blockquotes and code blocks are not wrapped in `span.mention` for me.

**Comment by terminalmage** [comment]
Here's what I'm seeing:

![slack_mention](https://cloud.githubusercontent.com/assets/328598/9159581/d77ea3d6-3ef0-11e5-93f1-f2089dd5af27.png)

Weirdly enough, `span.mention` has a `background` attribute of [#61485e](https://duckduckgo.com/?q=%2361485e&ia=answer), which _should_ be correct... But instead I'm seeing magenta. CSS is not my strong suit though, so perhaps some other CSS code is interacting to produce that result.

**Comment by laCour** [comment]
Ah, alright. This is due to how I hackishly styled code blocks and blockquotes. Currently the entire blocks have filters applied to them which invert their colors and rotate the hue (this is why the `span.mention` element has the correct color, but it is not being displayed as such). This is part of [_hacks.scss](https://github.com/laCour/slack-night-mode/blob/master/scss/modules/_hacks.scss).

Later today I'll definitely properly override these styles. This is easier with the newer Sass layout; my hackish filter method of doing this is a remnant from before.

**Comment by terminalmage** [comment]
OK, I'm seeing the below in normal mentions too, don't know if it's related. The username should show as white here.

![slack_mention](https://cloud.githubusercontent.com/assets/328598/9176973/07588690-3f54-11e5-84de-ff7aab93da16.png)

**Comment by terminalmage** [comment]
And the plot thickens with that last one. Mentions without a leading "@" look fine, slack must just be using a different span class for mentions with the leading "@".

**Comment by laCour** [comment]
I noticed that but couldn't figure out what caused the difference--thanks!

**Comment by terminalmage** [comment]
No prob! Just noticed this myself.
