### ISSUE TITLE
[Threads][Dark-Theme] Input text is dark on dark

### ISSUE THREAD

**Issue by bew** [laCour/slack-night-mode#100]
In the new threads panel, input text is black too, making it hard to read : 
![issue-slack-threads](https://cloud.githubusercontent.com/assets/9730330/22152940/6527f5d6-df25-11e6-92be-c4ad89810108.png)

Thanks!

**Comment by mufid** [comment]
Hi, i made a quick fix in #101. Could @laCour confirm this working and merge? Thanks!

**Comment by laCour** [comment]
Confirmed and updated.
