### ISSUE TITLE
Thread becomes unreadable when is not hovered

### ISSUE THREAD

**Issue by mufid** [laCour/slack-night-mode#102]
Is this expected? If user want to read what she/he writes, she/he must hover the mouseover the text area.

I attached my screen capture for the case.

![2017-02-02_10-51-13](https://cloud.githubusercontent.com/assets/430505/22536605/ae2ce236-e935-11e6-87ad-29ebba0ed333.gif)

**Comment by laCour** [comment]
To confirm the theme is updated, please try updating the theme manually on [userstyles.org](https://userstyles.org/styles/117475/slack-night-mode-black).

I'm unable to replicate this on Chrome/Firefox. What browser is this happening on?

**Comment by mufid** [comment]
Hi, i am using Windows 7 64-bit with Google Chrome Version 55.0.2883.87. I can assure that i am using the latest version of Stylish and the theme.
