### ISSUE TITLE
Highlighted messages are unstyled

### ISSUE THREAD

**Issue by utrack** [laCour/slack-night-mode#107]
Current style of highlighted messages makes them unreadable. Here's CSS:
```
ts-message.show_recap:not(.is_pinned) {
    background: #F3FAF6;
}
```

Example:
![scrot-20170320_114119](https://cloud.githubusercontent.com/assets/3862920/24092894/46aad54a-0d62-11e7-8181-0e2c5e9ffb0e.jpg)

**Comment by laCour** [comment]
Thanks for reporting this! An [update](https://userstyles.org/styles/117475/slack-night-mode-black) has been released.
