### ISSUE TITLE
Search field has white background

### ISSUE THREAD

**Issue by deep-programmer** [laCour/slack-night-mode#108]
Hi,

On default loading, the search box on top-right corner has a white background with 'Search' text in foreground as below:
![slack_search_white_bkgd_2](https://cloud.githubusercontent.com/assets/26603964/24542348/f1460146-1618-11e7-9d82-cd3b311f3171.png)

On clicking it, it expands as shown below:
![slack_search_expanded](https://cloud.githubusercontent.com/assets/26603964/24542365/fd1b18ee-1618-11e7-80c5-b90312a2df53.png)

When it collapses back again though, the white background doesn't appear anymore:
![slack_search_black_bkgd](https://cloud.githubusercontent.com/assets/26603964/24542478/6b335044-1619-11e7-9cd5-004e98f85434.png)

It would be nice if the search space has a white background, matching remaining page, on initial loading itself.

**Comment by laCour** [comment]
Thanks for reporting this! An [update](https://userstyles.org/styles/117475/slack-night-mode-black) has been released.
