### ISSUE TITLE
Wrong comment message color when sharing a message

### ISSUE THREAD

**Issue by Any1s** [laCour/slack-night-mode#115]
Screenshot:

![slack-night-mode-share-bug](https://user-images.githubusercontent.com/10657078/28985380-8bd6379c-7962-11e7-9dce-c157f27758a4.png)

The text is barely visible. I believe it should have a color value of #f0d9ed? I fixed it for me by adding the following rule to the stylesheet:

`.inline_message_input_container .message_input { color: #f0d9ed; }`

I was about to create a pull request but I'm not too familiar with SCSS and couldn't figure out where to put this rule in the sources while adhering to the existing structure, sorry.

Edit: Firefox 54.0.1 on Linux, if that makes any difference.

PS.: Thanks for this theme, I use it every day.

**Comment by laCour** [comment]
:beers: Thanks for your report! This has been fixed in the latest release.

Glad you find the theme useful!
