### ISSUE TITLE
Direct Messages Have Text Highlighting

### ISSUE THREAD

**Issue by spendrake** [laCour/slack-night-mode#116]
This is a weird issue, but I imagine small. When going to direct messages, the text get's highlighted in a dark color, rather than the bar getting highlighted like with channels.
![slack_2017-08-15_14-28-11](https://user-images.githubusercontent.com/22462054/29337953-3a2dccb6-81c8-11e7-8aa4-5c51878a039b.png)

**Comment by spendrake** [comment]
Not sure if you fixed it, or it stopped, but the issue no longer occurs!

**Comment by laCour** [comment]
@speterson2814 I haven't fixed this yet, so this is likely a change on Slack's end that caused the styling to work again. I'll investigate this later today when I update the theme.

**Comment by laCour** [comment]
This should be fixed now. Thanks for your report!
