### ISSUE TITLE
Purple sidebar

### ISSUE THREAD

**Issue by NeckBeardPrince** [laCour/slack-night-mode#117]
Now getting a purple sidebar, Slack must've pushed some update.

**Comment by Saamy88** [comment]
It happened to me too.

**Comment by asaada-r7** [comment]
you can manually set the sidebar background color in the slack settings to the old/correct color by setting the `Column BG` color to `#363636`

**Comment by laCour** [comment]
Thanks for your reports. :beers: This is fixed in the latest release.
