### ISSUE TITLE
Channel Topic background not styling properly -  2017-09-12

### ISSUE THREAD

**Issue by an-ghinid** [laCour/slack-night-mode#119]
As of 2017-09-12 I'm seeing a solid white background - see below image for reference.
![capture](https://user-images.githubusercontent.com/1761512/30343461-9b87ce24-97f5-11e7-9843-c640c61de1b5.PNG)

**Comment by cornfeedhobo** [comment]
same with `@` mentions

**Comment by Duroxxigar** [comment]
The @ mentions are pretty much blinding.

**Comment by laCour** [comment]
I've released an update with the fix for this, as well as mentions. Thanks for filing an issue!
