### ISSUE TITLE
About Channel styling issues.

### ISSUE THREAD

**Issue by andrewcartwright1** [laCour/slack-night-mode#121]
See attached images, Noticed these on the sidebar in about channel 😃 

![zappshot - 2017-09-15_09-29-36-am](https://user-images.githubusercontent.com/10059155/30473449-67c1fc4a-99f8-11e7-84cd-f06003ff1f04.png)
![zappshot - 2017-09-15_09-27-56-am](https://user-images.githubusercontent.com/10059155/30473448-67bfe5c2-99f8-11e7-8324-e82f02adea46.png)
![zappshot - 2017-09-15_09-27-45-am](https://user-images.githubusercontent.com/10059155/30473450-67da9228-99f8-11e7-8085-5f2306c617b9.png)

**Comment by laCour** [comment]
Thanks for reporting this! Let me know if the latest release has fixed this. I don't have any channels with highlights, so I was unable to tell.
