### ISSUE TITLE
Beta 3 Desktop load CSS

### ISSUE THREAD

**Issue by aalvarado** [laCour/slack-night-mode#125]
There's an open issue for a way to load the CSS via a hack https://github.com/laCour/slack-night-mode/issues/73 on this issue.

~~The hack however does not work in Beta 3.~~ i assumed it didn't work.

This issue is so we can track a way to do it in this new version

**Comment by x0rsw1tch** [comment]
I've tried a couple of things today without success....

- Adding the CSS to one of the font LESS files, nope.
- Trying various post-load browser events to trigger the promise, nope.
- Adding stylesheet entries (local and remote) to index.jade, nope.

Gonna see if I can figure out a way to enable devtools and try some things from there.

**Comment by laCour** [comment]
The original patch still seems to work in `ssb-interop.js`, though there are some style issues with the sidebar that need fixing.

Path on Windows:
```
%LOCALAPPDATA%\slack\app-3.0.0-beta32161c032\resources\app.asar.unpacked\src\static\ssb-interop.js
```
![image](https://user-images.githubusercontent.com/126202/32308483-c1ae8cfa-bf4b-11e7-98b5-592ebca87bf5.png)

There's not a beta version out yet for Linux, and I'm unable to test if this works on a Mac.

**Comment by x0rsw1tch** [comment]
For whatever reason the CSS file I had on my apache server was not receiving the request (CSO issue?) per access.log. 

I managed to get it working by using a local file, with this code in ssb-interop.js. I would prefer it to work with a remote file, but can live with this for now.

```
 document.addEventListener('DOMContentLoaded', function() {
  var fs = require('fs'),
  filePath = 'D:/slack-dark.css';
  fs.readFile(filePath, {encoding: 'utf-8'}, function(err, data) {
    if (!err) {
      var css = document.createElement('style')
      css.innerText = data;
      document.getElementsByTagName('head')[0].appendChild(css);
    }
  })
});
```

**Comment by aalvarado** [comment]
The only issue with this is that the theme needs to be edited before hand removing the mozilla css scope. other than that, I was able to get this working on `3.1.0`

**Comment by laCour** [comment]
There is a directory containing the themes without any moz scoping: https://github.com/laCour/slack-night-mode/tree/master/css/raw
