### ISSUE TITLE
Question regarding license of hack

### ISSUE THREAD

**Issue by shlomi-noach** [laCour/slack-night-mode#126]
Hello @laCour! Thank you for the wonderful hack at https://github.com/laCour/slack-night-mode/issues/73#issuecomment-287467332, quoting:

```
document.addEventListener('DOMContentLoaded', function() {
 $.ajax({
   url: 'https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css',
   success: function(css) {
     $("<style></style>").appendTo('head').html(css);
   }
 });
});
```

I'm wondering if this piece of code is licensed. 

I'd like to set up my own CSS changes to Slack, and use this hack for applying them. I can either create my own JavaScript code to load my CSS, but, since I found yours, I prefer to acknowledge your work. For that I'd need to know the license by which you publish you hack. I normally license my work under MIT which is one of the most permissive licenses and common within the JavaScript community.

Please let me know your thoughts,
Thank you!

**Comment by laCour** [comment]
Hey @shlomi-noach, thanks for asking! All my snippets of code in issues in this repository and code within the repository is released to the public domain under [CC0](https://www.gnu.org/licenses/license-list.html#CC0) ([full text](https://github.com/laCour/slack-night-mode/blob/master/COPYING.txt)). I do not request any attribution though it would be appreciated.

**Comment by shlomi-noach** [comment]
Thank you! An attribution is obviously in place.

**Comment by shlomi-noach** [comment]
Please see https://github.com/openark/custom-slack-css
Thank you!

**Comment by laCour** [comment]
Great styles and project! Thanks again for checking the licensing. 🍻

**Comment by CuriousFurBytes** [comment]
I also have a custom style, though CSS isn't really the thing I'm best at so there might be better ways to do what I did.
I didn't add you to the Credits but you actually inspired me too, sorry for forgetting about you. I'll be adding it asap.
