### ISSUE TITLE
Porting this scheme to solarized

### ISSUE THREAD

**Issue by vandr0iy** [laCour/slack-night-mode#128]
Hi @laCour , great theme you got here!
I ported it to the solarized colours, please [check it out.](https://github.com/vandr0iy/slack-fully-solarized)

Since I'm not a frequent css user what I did was taking the compiled .css file from your .scss sources, formatting it and 
regex-replacing all the colours in it from the shell with the ones that looked the closest - or the nicest :) I'm quite sure it can be done in a better way, though

Could you, please, add it to the variants in your description?

**Comment by Lemmmy** [comment]
You can make a theme by adding a variant [here](https://github.com/laCour/slack-night-mode/tree/master/scss/themes) :) All you need to do is change the variables and recompile using the makefile. This makes it easier to update all the variants at once when Slack changes their code.

**Comment by nysos3** [comment]
Solarized Light and Dark variants are already included. (I'm aware this thread is old. Closing.)
