### ISSUE TITLE
New slack updates leave unthemed CSS

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#13]
1. Clicking on a username brings up the Team Directory pane on the right, which has an unthemed background.
2. ~~The drop-down menu which appears when you click the inverted chevron in the upper-left (near your name) to access your preferences, sign out, etc. has an unthemed border. **NOTE:** The same issue occurs the the "three dots" button in the upper right of the page is clicked.~~
3. ~~The list of usernames which appears when showing matching usernames in the chat input box has an unthemed background.~~

**Comment by terminalmage** [comment]
Actually, to trigger number 1 above, you can't just click a username in the chat,  you need to just get to the Team Directory, as this is where the unthemed (white) background shows.

Also, another instance of issue number 2 can be seen when clicking on a username in the chat.

**Comment by laCour** [comment]
I'm unable to reproduce 2 or 3 on Firefox/Chrome. Are you using the latest version?

Thanks for the help.

**Comment by terminalmage** [comment]
You're right, n00b mistake not checking for an update first.

**Comment by laCour** [comment]
Haha, less work for me. I've released an update which fixes this.

**Comment by terminalmage** [comment]
OK, not showing up as an update yet in the extension, will check back later today to confirm. Thanks!
