### ISSUE TITLE
Group mentions have a white background

### ISSUE THREAD

**Issue by ifvictr** [laCour/slack-night-mode#132]
![capture](https://user-images.githubusercontent.com/10110245/34653083-cb02e20e-f39b-11e7-97f7-dade86797890.PNG)

**Comment by laCour** [comment]
Thanks for spotting this. ~Could you provide me with the class of this element?~ Found it.

**Comment by cornfeedhobo** [comment]
@laCour Thanks for maintaining this ever-evolving theme! any chance this could get some attention when you get a chance?
