### ISSUE TITLE
Primary message text styles broken

### ISSUE THREAD

**Issue by laCour** [laCour/slack-night-mode#134]
Primary message styles are broken, so messages are hard to read. I'll be making a release shortly.

**Comment by laCour** [comment]
This is a significantly large style migration of many Slack components, primarily affecting messaging.

I've updated a large chunk of the styles in the latest release, but there are still some styles left which need addressing.

**Comment by sandra1n** [comment]
Thanks. It works

**Comment by vg** [comment]
plain text snippets are still unreadable
