### ISSUE TITLE
Desktop App foreground color makes text unreadable

### ISSUE THREAD

**Issue by yourbuddypal** [laCour/slack-night-mode#135]
I'm on Win10 using the desktop app with the "desktop hack" that downloads the dark theme via a DomContentLoaded event.  When I restarted the app today, the Dark theme does still get applied, but I noticed that the foreground color of all the text is not being set to a light color.  The dark (black?) text on the dark background is not readable.

I opened Slack in the browser and added the theme in Stylish and it seemed to be working without issue.

**Comment by ChipWolf** [comment]
Lol, no. You just need this sidebar theme, the desktop hack requires it #363636,#444A47,#D39B46,#FFFFFF,#434745,#FFFFFF,#99D04A,#DB6668

**Comment by dairennlombard** [comment]
I don't think this issue was correctly understood.

It's not the sidebar that's broken, it's the MAIN screen:

https://screenshot.net/n27yvc7

It used to look like this:

https://screenshot.net/yr78vsj

I don't know why Some Slack accounts are affected but not others, but, thanks to this, I basically can't read anything anymore.

(I've worked around this for now by also using the "Stylish" FireFox plugin.)

**Comment by TheMarf** [comment]
Having similar issue as others have mentioned:

One team looks normal as expected: https://i.imgur.com/ZPXhuh3.png

with the dark theme, but all other teams are a bit out of sorts looking like this:

https://i.imgur.com/P9vFVDK.png

Gray font, on a gray background, with very bright white highlighting.

**Comment by ZigMeowNyan** [comment]
So, the recommended link (https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css) is from the CDN. But it's not returning the same CSS as what' s in the repo (https://github.com/laCour/slack-night-mode/blob/master/css/raw/black.css). Notably, the `c-message__body` class isn't showing up for me. Which would explain why the text in the theme isn't working. Is there a better way to grab the file and skip the CDN manglement?

**Comment by ZigMeowNyan** [comment]
Ah, try https://raw.githubusercontent.com/laCour/slack-night-mode/master/css/raw/black.css. That gets the file skipping the CDN.

**Comment by ZigMeowNyan** [comment]
Seems the above class was added in commit d1415d3 but hasn't propogated out to the CDN?

**Comment by TheMarf** [comment]
Swapping the URL to the one provided seemed to do the trick for me.

**Comment by yourbuddypal** [comment]
Seems to be a CDN caching issue preventing the most recent version from pulling down.

Either update the URL sugested by mr Zig above `https://raw.githubusercontent.com/laCour/slack-night-mode/master/css/raw/black.css` or as seen here:
https://github.com/laCour/slack-night-mode/issues/73#issuecomment-357048740

**Comment by ChipWolf** [comment]
Apologies, I changed the desktop hack script to use the githubusercontent domain. Issue sovled.
