### ISSUE TITLE
Posts issue

### ISSUE THREAD

**Issue by iksela** [laCour/slack-night-mode#137]
Posts aren't styled when displayed inside a channel.

![image](https://user-images.githubusercontent.com/501800/35269672-0761171e-002d-11e8-853e-5c3f14f5e71a.png)

*Env:* slack 3.0.5 / windows 10 / https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css

**Comment by mastermel** [comment]
I'm pretty sure this was recently fixed in #168. If you're still seeing the issue after updating to the latest, let us know!

**Comment by cryocaustik** [comment]
@laCour looks like this is an issue with the v3.3.7 update. 

From what  I am seeing, `.c-pillow_file_container` has it's background color set to `#fff`
