### ISSUE TITLE
Howto change chat text font

### ISSUE THREAD

**Issue by jlanza** [laCour/slack-night-mode#138]
At least in my case it seems that all text is bold or with a kind of shadow. What are the properties to change it? could you please give some hints?

**Comment by laCour** [comment]
Could you provide me with a screenshot of an example so that I know what styles you're referencing?

**Comment by mastermel** [comment]
@jlanza closing this for now as it's been over a month. If you're still seeing an issue, please re-open with a screenshot of what you're seeing, thanks!
