### ISSUE TITLE
"All Unreads" section headings unstyled

### ISSUE THREAD

**Issue by Line-Noise** [laCour/slack-night-mode#150]
When using keyboard shortcuts for "All Unreads" (`Enter` to show unreads, `r` to mark as read) the channel section headings are unstyled. The class for the `div` is `unread_group_header display_flex justify_content_between`.

**Comment by mastermel** [comment]
Hey @Line-Noise, I'm not super familiar with the keyboard controls for "All Unreads", but examining that part of Slack on the latest version today it appears that the channel headers are being themed correctly. If that's not the case, can you re-open this and include a screenshot of what you're seeing?

**Comment by Line-Noise** [comment]
![screenshot from 2018-05-17 09-48-15](https://user-images.githubusercontent.com/2012813/40149695-7417952e-59b8-11e8-852b-6b229b4d76ee.png)

I have the latest version installed on May 14. It's still happening. I've attached a screenshot.

* If you have multiple channels with unread messages click on `All Unreads` at the top of the Channel list pane.
* A list of channels and unread messages will be displayed in the message pane.
* On your keyboard hit the `r` key to mark the first unread channel as "read".
* That channel will collapse and the next unread channel will be highlighted.
* This new highlighted channel name line is unstyled. (Note, clicking on the "Mark as Read" button will style the channel header correctly. Only the keyboard shortcut causes it.)
* The remaining read and unread channels will be styled correctly (apart from the "Mark as Read" button).

Thanks for your work on this theme! It makes Slack usable without burning out my retinas!

**Comment by mastermel** [comment]
Awesome, thank you @Line-Noise, I'll look for an opportunity to repro and fix!
