### ISSUE TITLE
Username mentions in channel topics not themed

### ISSUE THREAD

**Issue by BHSPitMonkey** [laCour/slack-night-mode#173]
Title says it all: If you include a user `@mention` in a channel topic, it doesn't get the usual treatment and stands out.

(Thanks for this awesome theme!)

**Comment by Lemmmy** [comment]
Screenshot: ![](https://you.wouldnot.download/a-silver.png)
Classes: `internal_member_link ts_tip ts_tip_top ts_tip_float ts_tip_member mention ts_tip_hidden`

Most likely class seems to be `internal_member_link` (applies background + colour)
