### ISSUE TITLE
the font in the input-box for threads is not stylized and thus is really faint

### ISSUE THREAD

**Issue by luckyvalentine** [laCour/slack-night-mode#184]
this is the best "night mode for slack" that I've seen so far.  the one issue i've seen is that the text entry box in the 'threads' sidebar isn't stylized and thus its really feint / hard to read.  

I looked through the .CSS to see if there is something simple I could change but I couldn't find anything.

Any fix for this?  I use threads a LOT...

Thanks!

**Comment by luckyvalentine** [comment]
actually, as I look at it ... it's not the font, it's the color of the input box.  the color of the threaded input box did not get colorized to grey like the main input box, so the white text doesn't show well on the white threaded input box

**Comment by pseeth** [comment]
Hmm, I'm still getting this error using the latest version. Did they change the id of the box or something?

![image](https://user-images.githubusercontent.com/1054895/51642381-e8b1f480-1f1d-11e9-841c-7952b8adfeba.png)

**Comment by asaada83** [comment]
This broke in the latest update v3.3.7 but was working fine before. cc @mastermel

**Comment by laCour** [comment]
Oops, see #206.
