### ISSUE TITLE
Search panel is not stylized

### ISSUE THREAD

**Issue by bastienunity** [laCour/slack-night-mode#186]
Looks like slack changed the search panel recently, it is not getting stylized anymore and stays with a white background while the font is still gray/white which makes it almost unusable.

**Comment by mastermel** [comment]
Thanks for reporting this @bastienunity!

We did a new release of the style just two days ago. Among other things it included corrections to the new search box, making it look better and fit the dark style. Could you try updating the stylesheets you're using to the latest and see if you still have any issues?

**Comment by bastienunity** [comment]
I've updated yesterday to get the fix for the threads, which is working fine now but the search box is still broken for me.
![search-box](https://user-images.githubusercontent.com/29260853/45182440-33d99e00-b1ef-11e8-885d-9fbd56c1e4de.png)
I'm using the desktop version with the hack inside ssb-interop.js in case it helps.
Tested with both 3.2.0 and 3.3.1 releases of Slack.

**Comment by DuBistKomisch** [comment]
Also updated to the latest available on userstyles, search panel is still messed up like before. Using it in Firefox.
