### ISSUE TITLE
Can't have multiple accounts

### ISSUE THREAD

**Issue by hmoreau94** [laCour/slack-night-mode#198]
Hey I was trying to have multiple accounts and it simply doesn't work: I'm redirected to slack.com where I need to log in and from there it never redirects me to Sblack (even if I force to open the link with sblack).

**Comment by ideologysec** [comment]
This isn't the place to file sblack bugs. :) This is a user style using CSS to change Slack inside a web browser, or with some hackery inside the official desktop client.

**Comment by laCour** [comment]
Closing because this is unrelated. Please open a new issue if you encounter an issue with these styles!
