### ISSUE TITLE
Font family in main chat window differs from left navbar

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#2]
The font-family `"Helvetica Neue", Helvetica, "Segoe UI", Tahoma, Arial, sans-serifsans-serif` is overriding the correct one in several places.

In this particular instance, the offending line is [here](https://github.com/laCour/slack-night-mode/blob/e9e0cd9/css/default.css#L1091), but the same font-family is also defined [here](https://github.com/laCour/slack-night-mode/blob/e9e0cd9/css/default.css#L440) and [here](https://github.com/laCour/slack-night-mode/blob/e9e0cd9/css/default.css#L1120), as well as the exact same line numbers in [css/variants/black.css](https://github.com/laCour/slack-night-mode/blob/e9e0cd9/css/variants/black.css).

**Comment by terminalmage** [comment]
Has this commit made it to an official update? Stylish is telling me that the style is up to date, but I'm still seeing the Helvetica font in the main chat window.

If you haven't pushed an update yet, disregard, but if you have then you might need to take another look. Thanks!

**Comment by laCour** [comment]
This has been pushed in an update, so the fix likely doesn't work, I wasn't able to easily test to make sure that the fix worked. I know of a better method of doing this that will work, which I'll apply during the next update. Thanks for letting me know!

**Comment by terminalmage** [comment]
Can confirm the fix, thanks!
