### ISSUE TITLE
New thread replies are unreadable

### ISSUE THREAD

**Issue by kareemlukitomo** [laCour/slack-night-mode#226]
![image](https://user-images.githubusercontent.com/16204162/57896347-796c6180-787a-11e9-8794-7290a921a2d4.png)

On Hackintosh High Sierra 10.13.6. But IIRC my other laptop with Mojave Native Dark theme enabled is unreadable as well.

**Comment by mastermel** [comment]
This has been improved in the latest release! Please let us know if you continue to see any issues after updating 😄
