### ISSUE TITLE
Threads view with latest slack 3.4 has white background

### ISSUE THREAD

**Issue by ovidiubuligan** [laCour/slack-night-mode#228]
![image](https://user-images.githubusercontent.com/4757459/58003780-30224900-7aea-11e9-9168-504091608a65.png)

**Comment by ghost** [comment]
See: https://github.com/laCour/slack-night-mode/pull/224

**Comment by krazyito65** [comment]
> See: #224

How does this help?  Still same issue.

**Comment by mastermel** [comment]
This has been improved in the latest release! Please let us know if you continue to see any issues after updating 😄
