### ISSUE TITLE
Unthemed dark usernames

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#24]
The anchor styling for user name seems to have changed.

**Comment by laCour** [comment]
Could you provide a screenshot? Where are you seeing this?

**Comment by terminalmage** [comment]
Here's an example:

![screenshot 2015-11-13 at 11 56 45](https://cloud.githubusercontent.com/assets/328598/11153323/c4458ef8-89fd-11e5-85b6-125df3335b9f.png)

**Comment by laCour** [comment]
I've released the fix for this issue, thanks for reporting it. You may have to refresh userstyles a few times for it to recognize you have an outdated version.

**Comment by terminalmage** [comment]
I no longer update via userstyles.org, Stylish for Chrome lets you check for and install updates for styles from within the extension options. Sometimes there's a bit of a delay from when you push the update, but in this case ~2 hrs later the update did show up. After installing it, I can confirm the usernames are now light again.

Thanks!
