### ISSUE TITLE
Light-purple background absent from highlights

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#26]
Examples:

![screenshot 2015-11-18 at 14 57 58](https://cloud.githubusercontent.com/assets/328598/11254168/e4c2fc32-8e04-11e5-9b88-b50bdeb972c5.png)

![screenshot 2015-11-18 at 15 02 33](https://cloud.githubusercontent.com/assets/328598/11254304/821ac41a-8e05-11e5-983e-7408c557a6a6.png)

I recall that before, they had light-purple backgrounds to make them stand out. As it is, they no longer stand out in normal chat usage as the color of the username is either the same or virtually indisguishable from the rest of the text:

If this was a conscious design choice, perhaps it may be better to alter the text color to better distinguish it from normal chat text. Otherwise, restoring the light-purple background would make the highlights stand out much better.

**Comment by laCour** [comment]
Released a fix, thanks!
