### ISSUE TITLE
Style adjacent new messages and day divider

### ISSUE THREAD

**Issue by laCour** [laCour/slack-night-mode#30]
`#msgs_div .unread_divider.adjacent_to_date` has not been styled:

![divider](https://cloud.githubusercontent.com/assets/126202/11432937/661c40a2-9474-11e5-9e54-7959a8640ef7.png)

**Comment by terminalmage** [comment]
Yep, just noticed this myself. Slack sure does like to change their CSS often.

**Comment by laCour** [comment]
Yeah they do!
