### ISSUE TITLE
Text is hard to read in post editor

### ISSUE THREAD

**Issue by Justin-Credible** [laCour/slack-night-mode#38]
The black text for lists and paragraph text is hard to read in the post editor. It would be nice if the post editor's text color matched the chat text color.

![screen shot 2016-01-22 at 11 45 55 am](https://cloud.githubusercontent.com/assets/1243565/12521173/dcfb5478-c0fd-11e5-9659-f004f3074f24.png)

**Comment by laCour** [comment]
Thanks! :+1:  Looks like they just changed the main selector.

**Comment by Justin-Credible** [comment]
Thanks for the quick fix!  🎉
