### ISSUE TITLE
White background on channel toolbar (Aubergine)

### ISSUE THREAD

**Issue by Justin-Credible** [laCour/slack-night-mode#40]
The channel's toolbar and widget have white backgrounds and the channel title text is black on the Aubergine variant. Everything looks fine on the Black variant though.

![screen shot 2016-03-10 at 9 54 32 am](https://cloud.githubusercontent.com/assets/1243565/13679060/a8c3831e-e6a6-11e5-9f93-cbea542a64b4.png)

**Comment by laCour** [comment]
That looks like an older version. Please confirm if updating corrects the issue.

**Comment by Justin-Credible** [comment]
For some reason the "Check for Updates" button in Stylish was returning with no updates available on Chrome on Mac OS, but it was working on Chrome on Windows.

I had to remove the style from stylish and reinstall on the Mac, and now it is working properly.

Thanks.

**Comment by laCour** [comment]
That seems to be a checksum caching issue on their end that a lot of people have encountered. I'll see if I can get it resolved. Thanks for letting me know!
