### ISSUE TITLE
Quick Switcher (Ctrl-K) has unthemed parts

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#41]
![slack](https://cloud.githubusercontent.com/assets/328598/13788080/7a5f8612-eaac-11e5-98bf-3425c348c48d.png)

**Comment by laCour** [comment]
Always forget to check that, thanks for letting me know. I'll get a new release out tonight.

**Comment by terminalmage** [comment]
No prob... I keep saying I'm going to make time to contribute these fixes myself, any helpful info you could give me so that I can comply with your style preferences?

**Comment by laCour** [comment]
Currently I just use [scss-lint](https://github.com/brigade/scss-lint/). There's a configuration file for it in the repo with my style preferences. If you don't use Ruby, installing a gem for that can be a pain, so I plan on setting up Hound CI to keep pull requests consistent. I'll write a more in-depth contribution guide in the near future.

But for now, so long as indentation is consistent and you use the existing color variables, it's all good!
