### ISSUE TITLE
Improve styling of main input box

### ISSUE THREAD

**Issue by shmup** [laCour/slack-night-mode#48]
It looks very nice by default, and on hover. I think its focus style could be improved.

I don't have any concrete ideas yet, I've dabbled some in adjusting the color at a minimum.
I just think 2 pixels of solid black borders looks _off_ when its focused.

An easy _right now_ fix is to do something about the doubled up border where the button means the input.

![image](https://cloud.githubusercontent.com/assets/118710/14247647/960b116a-fa3d-11e5-930b-8a5dae772d13.png)

**Comment by laCour** [comment]
I've improved the border colors a bit, and have fixed the doubled-up border. An update has been pushed with these changes.

Let me know if you have any more suggestions for improving this (e.g. recommended colors). Thanks!

**Comment by shmup** [comment]
Yeah it's definitely better. I say close the issue.

I think something could be better when you mouse over the [+] left of the input. At the border, where it connects.

Like right now it's good, but it's not _perfect_, yanno?

**Comment by laCour** [comment]
I agree; I'll improve the file button in the next release. Thanks! :beers:
