### ISSUE TITLE
div#client_body::before is unthemed

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#55]
Notice the white line at the top, near the channel name.

![slack](https://cloud.githubusercontent.com/assets/328598/15192232/ed6e3b32-177d-11e6-9358-364b37b42145.png)

**Comment by laCour** [comment]
A recent update should have taken care of this (see #53). Though as usual userstyle's updating isn't the best, and their site is currently having issues, so you might want to manually update to confirm: https://raw.githubusercontent.com/laCour/slack-night-mode/master/css/variants/aubergine.css

If you're using Stylish with a Chromium-based browser, you'll update manually by importing a Mozilla format style:

![image](https://cloud.githubusercontent.com/assets/126202/15200564/3c4fb164-17a5-11e6-83fa-03adcb99e628.png)

**Comment by terminalmage** [comment]
So, this is kinda weird, I installed an update and refreshed Slack before I posted this report (as I always do when I find unthemed elements), and it didn't change anything. So, I deleted the theme and reinstalled from the userstyles.org page and now it's fine.

Sorry for the noise.
