### ISSUE TITLE
White Boxes

### ISSUE THREAD

**Issue by tdweng** [laCour/slack-night-mode#57]
A few mods i made to get rid of newly white boxes that appear:
# client_body:not(.onboarding):before {

```
position: static;
```

}
# footer:not(.footer_msg_input) {

```
background: #222
```

}

**Comment by laCour** [comment]
Thanks for the help! I've released an update that fixes this issue already however. Let me know if updating fixes the issue for you.

Cheers! :beers:

**Comment by tdweng** [comment]
Your updates did fix the issue thanks. I tried updating from the plugin, but seems i had to go to the stylish page and update from there before it would actually update it.

**Comment by laCour** [comment]
Great! Many people have been encountering the same update issue. I'll see if I can get them to fix it.
