### ISSUE TITLE
Default text color for snippets has changed

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#70]
Haven't investigated to lock down precisely which CSS change caused this, but the default text color in snippets is now dark grey, at least in the aubergine variant of the style.

**Comment by laCour** [comment]
Fixed, thanks! 🍻

**Comment by terminalmage** [comment]
Confirmed. Updated via userstyles.org. Looks like the Stylish extension is still lagging behind, I got an update via the extensions update mechanism and it didn't contain this fix.
