### ISSUE TITLE
Text in chat box before typing is too dark

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#75]
![background](https://cloud.githubusercontent.com/assets/328598/17940101/290f17c0-69f3-11e6-84b3-8cffeefda08b.png)

Seems to be a recent change by Slack. There's not enough contrast there with the current color.

**Comment by terminalmage** [comment]
Looks like the CSS changed for the typing notification as well, FYI. It's grey instead of light purple.

![2016-08-24-131500_3200x1800_scrot](https://cloud.githubusercontent.com/assets/328598/17942506/4ba5dac6-69fd-11e6-9744-e895ae3b5db2.png)

**Comment by laCour** [comment]
Thanks! 🍻 An update has been released fixing this issue, as well as #74.

**Comment by terminalmage** [comment]
Thanks! Just updated, but it looks like the contrast between channels with and without new messages is a bit diminished.

![contrast](https://cloud.githubusercontent.com/assets/328598/17971156/3014a56a-6a9f-11e6-8add-41df29214fe3.png)

It's easier to see when you look at it closely, like this, but on a HIDPI screen, when looking at the main chat window, it's hard to see if any channels have new messages.
