### ISSUE TITLE
Using domain(slack.com) darkens non-chat pages

### ISSUE THREAD

**Issue by devkev** [laCour/slack-night-mode#76]
eg. https://slack.com/jobs/dept/engineering is hard to read.

Would it be better to instead use something like `regexp("https://[^./]*\\.slack\\.com/.*")`?  This should match the chat interface (for any team), but without affecting slack's main/corporate page...

**Comment by laCour** [comment]
Thanks for the regex, I wasn't aware `@document` supported it. 🍻
