### ISSUE TITLE
ephemeral messages have a light background

### ISSUE THREAD

**Issue by renatofrota** [laCour/slack-night-mode#82]
Ephemeral messages are those generated by slackbot when you use command tools like: `/dnd 10 mins`

This fits nice here:

```
ts-message.ephemeral { background-color: #333; }
```

Very cool style btw! :+1:

**Comment by laCour** [comment]
Thanks! Is this a bug or a suggested enhancement? I'm not seeing any quirks with ephemeral messages using the latest release.

**Comment by renatofrota** [comment]
Bug. Screenshots, after typing `/dnd 123` (invalid command).

Default:

![screenshot-siteground slack com 2016-09-25 01-18-58](https://cloud.githubusercontent.com/assets/3386314/18812991/2a72ecd4-82be-11e6-9eee-8cdea71a8934.png)

With the change I proposed:

![screenshot-siteground slack com 2016-09-25 01-20-57](https://cloud.githubusercontent.com/assets/3386314/18812995/61b850da-82be-11e6-90ba-bb0ee82c890e.png)

**Comment by laCour** [comment]
Can you confirm that your style is updated via https://userstyles.org/styles/117475/slack-night-mode-black and that the issue persists?

I'm unable to replicate this issue on Firefox/Chromium. What browser is this?

**Comment by renatofrota** [comment]
I am very sorry!! The problem was on that piece between the desk and the chair (blame on me!)

I forgot my **own** userstyle do stylize ephemeral messages :trollface: 

https://userstyles.org/styles/127913/ds-improve-slack-com

It fits well on dark backgrounds now :wink: 

Thanks

**Comment by laCour** [comment]
Haha, it's all good, glad you found the cause. 👍
