### ISSUE TITLE
Channel preview text is darker than it should be

### ISSUE THREAD

**Issue by an-ghinid** [laCour/slack-night-mode#84]
![c48343a71fb4f9bad55db3172d0be169](https://cloud.githubusercontent.com/assets/1761512/18848961/a34ca846-8428-11e6-8287-5d21af2a2530.png)

See the above image for example, happening as of 26th September. Similar to previous issue #75

**Comment by laCour** [comment]
Thanks for reporting this! A fix has been released: https://userstyles.org/styles/101971/slack-night-mode
