### ISSUE TITLE
Left border on expanded attachments (links, images, etc.) changed class

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#88]
The new div class for these is `msg_inline_attachment_column column_border` but my CSS-fu is not strong enough for me to figure this out. Appreciate a heads-up when fixed so I can learn :smile:

**Comment by laCour** [comment]
Sorry about taking so long to get to this one! Previously I hadn't styled these since it would override plugin's custom attachment bar colors. This no longer is the case, however.

Let me know if you have any questions about adding styles, and if anything can be clarified in the contributor guide.
