### ISSUE TITLE
Theme applied to all websites

### ISSUE THREAD

**Issue by tdweng** [laCour/slack-night-mode#89]
Not sure if it is me or what but the theme gets applied to all my websites in chrome very annoying.

**Comment by StJohn3D** [comment]
Yes same here. The update fixed the issue with the top-bar in slack, Much appreciated! But I have to disable this style for now because it's affecting all websites making them unusable. I love this style and hope I can turn it back on soon. Thanks for maintaining it!

**Comment by tdweng** [comment]
i haven't looked what changed yet, but i had to install another theme and add this line to fix the bar at the top:

.channel_header {background: #282a2e; }

Hopeifully you can get this resolved soon because i do enjoy your theme.

**Comment by laCour** [comment]
Bizarre, thanks for reporting this. I've updated the theme without any changes and this seems to have fixed it (userstyles.org's URL restriction must have been corrupted). Please confirm whether updating corrects this.

**Comment by StJohn3D** [comment]
So I clicked manage, check for updates, installed update. Didn't fix it. Uninstalled, then reinstalled, problem corrected! Thank you so much, this style is the best!

**Comment by tdweng** [comment]
Whenever i update a theme in chrome i have to go to manage, click the little globe next to the theme name, which brings me to the stylish page and then click update/install from there otherwise it doesn't seem to update. Not sure why. It does seem everything is fixed now. I have to verify though on my other laptops when i get a chance.
