### ISSUE TITLE
Style not applying properly to message box as of 2016/12/15

### ISSUE THREAD

**Issue by an-ghinid** [laCour/slack-night-mode#91]
![image](https://cloud.githubusercontent.com/assets/1761512/21240411/15c35e9c-c303-11e6-9b3b-1218c71519f6.png)

As seen in the above image, the message box is incorrectly sized and is entirely white.

**Comment by Lemmmy** [comment]
![](https://shitty.download/hZE8nM.png)

**Comment by laCour** [comment]
Thanks for reporting this! 👍 

I've released a fix. Be sure to update via userstyles.org, since updating through the plugin page will likely not work due to their overly aggressive caching.
