### ISSUE TITLE
"About" Channel / Convo Heading box has white background

### ISSUE THREAD

**Issue by loopervfx** [laCour/slack-night-mode#96]
Please see attached screenshots for examples of where/when styling is missing in the sidebar header.

![slack convo](https://cloud.githubusercontent.com/assets/15337230/21773807/7060432e-d65e-11e6-9828-557379fc5dd0.png)
![slack chan](https://cloud.githubusercontent.com/assets/15337230/21773810/7243a708-d65e-11e6-8dd7-0522d69ff7a7.png)

thanks for the great theme
- landon

**Comment by loopervfx** [comment]
With some element inspection I was able to get the "black" variant of the stylish theme to look correct by adding these two lines:

`  #client-ui:not(.flexpane_redesign) #details_tab .heading{background: #222;}`
`  #client-ui:not(.flexpane_redesign) #flex_contents .heading{color: #fff;}`

I'm not very well versed in git but I cloned the repo, created a new branch, made the change to black.css, committed it, and tried to send pull request but i'm getting a permissions error when sending the pull request so wanted to put the update here as well. 

I'm guessing I am just not allowed to make pull requests unless you explicitly add me as a contributor? Let me know if that's the issue --and please forgive my lack of knowledge / experience here

**Comment by laCour** [comment]
Slack's latest update resolved this issue.

Thanks for your interest in contributing, you can find more information about how these styles are generated from [SCSS](http://sass-lang.com/guide) here: https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md Let me know if you have questions.

To make a pull request, you'll want to fork the repository first.
